config/routes.rb
XtcApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root  'static_pages#home'
  match '',           to: 'microposts#create',    via: :post
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/tentang',   to: 'static_pages#tentang',   via: 'get'
  match '/ketentuan', to: 'static_pages#ketentuan', via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'

  

end

app/views/shared/_depan.html.erb
<div class="container transparent">
	<div class="row-fluid">
		<div class="span12">
			<div class="row-fluid">
				
				<div class="span8">
					<%= image_tag("creatives_2.png", id: "img-rounded") %>
					<%#= image_tag("mantap.png", id: "img-rounded") %>
				</div>

				<div class="span4">
					<div id="form-signin">
						<%= form_for(:session, url: sessions_path) do |f| %>
						<%= f.text_field :email, placeholder: "Alamat email" %>

						<div class="row-fluid">
							<div class="span9">
								<%= f.password_field :password, placeholder: "Sandi" %>
							</div>
							<div class="span3">
								<%= f.submit "Masuk", :class => "btn btn-primary btn-block" %>
								<% end %>
							</div>
						</div>

						<% flash.each do |key, value| %>
						<%= content_tag(:div, value, class: "alert alert-#{key}") %>
						<% end %>		
					</div>

					<div id="form-signup">
						<h2>Gratis, silahkan daftar</h2>
						<%#= form_for(@user) do |f| %>
						<%= form_for(:user, url: users_path) do |f| %>
		        <%# flash.each do |key, value| %>
		        <%#= content_tag(:div, value, class: "alert alert-#{key}") %>
		        <%# end %>
		        <%#= render 'shared/error_messages', object: f.object %>
		        <%= render 'users/fields', f: f %>
		        <%= f.submit "Daftar", class: "btn btn-primary btn-block", "data-no-turbolink" => true %>
		        <% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<div id="konten">
	<h2>Curhatan</h2>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<center><%= will_paginate @feed_items %></center>
</div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<small><%= link_to feed_item.user.name, feed_item.user %></small>
  	</span>

  	<span class="content"><small><%= wrap(feed_item.content) %></small></span>
  	<span class="timestamp">
      <small><%= time_tag(feed_item.created_at, :format => 'Tanggal %d/%m/%Y Jam %R WIB') %></small>
  	</span>

  	<% if current_user?(feed_item.user) %>
    <small>
    	<%= link_to "Hapus", feed_item, 	method: :delete, data: { confirm: "Kamu yakin ?" }, title: feed_item.content %>
      </small>
  	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, url: root_path) do |f| %> 
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<% flash.each do |key, value| %>
	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

<%= f.text_area :content, placeholder: "Kirim status..." %>
</div>
<%= f.submit "Kirim", class: "btn btn-small btn-primary" %>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

    <div class="stats">
      <a href="<%= user_path(@user) %>">
        <strong id="microposts" class="stat">
          <%= @user.microposts.count %>
        </strong>
        <small>STATUS</small>
      </a>

      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          <%= @user.followed_users.count %>
        </strong>
        <small>PENGINTIP</small>
      </a>
      <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
        <small>DIINTIP</small>
      </a>
    <%#= render 'follow_form' if signed_in? %>
    <div id="stat-h">
      <%= render 'users/follow_form' if signed_in? %>
    </div>
    </div>
  
    

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 30), current_user %>

<h2><%= current_user.name %></h2>

<span>
	<small><%= link_to "Liat profil sendiri", current_user, :target => '_blank' %></small>
</span>