config/routes.rb
XtcApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root  'static_pages#home'
  match '',           to: 'microposts#create',    via: :post
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/tentang',   to: 'static_pages#tentang',   via: 'get'
  match '/ketentuan', to: 'static_pages#ketentuan', via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container transparent">
    <div class="row-fluid">
      <nav>
        <ul>
          <li><%= link_to "Tentang", tentang_path %></li>
          <li><%= link_to "Kontak", contact_path %></li>
          <li><%= link_to "Tolong", help_path %></li>
          <li><%= link_to "Ketentuan", ketentuan_path %></li>
          <li><small>&copy; <%= Time.now.year %> XTC - 808</small></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
    <div class="container">

      <%= link_to image_tag("creative_1.png", id: "img-header"), root_path, id: "brand"  %>
      <% if signed_in? %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Alvarium", root_path %></li>
          <li><%= link_to "Teman", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Akun<b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <!--<li><%#= link_to "Profil", current_user %></li>-->
              <li><%= link_to "Edit profil", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Keluar", signout_path, method: "delete" %></li>
            </ul>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= favicon_link_tag 'xtc.ico', rel: 'shortcut icon' %>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>